apiVersion: batch/v1
kind: Job
metadata:
  name: oc-scale-down-all
  namespace: oneiro
spec:
  template:
    spec:
      containers:
      - image: registry.redhat.io/openshift4/ose-cli
        imagePullPolicy: IfNotPresent
        command: ["sh", "-c", "/sleep/scale-down-all.sh"]
        name: ose-cli
        volumeMounts:
        - mountPath: /sleep
          name: bash-script
          readOnly: true
      serviceAccountName: sleep-monitor
      restartPolicy: Never
      volumes:
      - name: bash-script
        configMap:
          name: scale-down-all
          items:
            - key: scale-down-all.sh
              path: scale-down-all.sh
              mode: 0755
