apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sleep-monitor
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: sleep-monitor
subjects:
- kind: ServiceAccount
  name: sleep-monitor
  namespace: oneiro
